### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by snout-o** [Kurtz1993/ionic-minify#22] opened 2016-08-11 00:52 UTC
Hi

Probably I'm doing something wrong here but I get an install error when I run the npm install command. I thought it might be to do with specific folder permissions (e.g. node_modules, hooks/\* etc) but changing those permissions made no effect, even when running under sudo.

$ node --version
v0.12.4

The relevant error output in nom-debug.log is shown below, hope this helps:

> 106312 info install ionic-minify@2.0.9
> 106313 info postinstall ionic-minify@2.0.9
> 106314 verbose unsafe-perm in lifecycle false
> 106315 info ionic-minify@2.0.9 Failed to exec postinstall script
> 106316 verbose unlock done using /.../.npm/_locks/ionic-minify-8a16f1ba0057f9ac.lock for /<redacted>/node_modules/ionic-minify
> 106317 verbose stack Error: ionic-minify@2.0.9 postinstall: `node scripts/install.js`
> 106317 verbose stack Exit status 1
> 106317 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 106317 verbose stack     at EventEmitter.emit (events.js:110:17)
> 106317 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 106317 verbose stack     at ChildProcess.emit (events.js:110:17)
> 106317 verbose stack     at maybeClose (child_process.js:1015:16)
> 106317 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 106318 verbose pkgid ionic-minify@2.0.9
> 106319 verbose cwd /.../
> 106320 error Darwin 15.6.0
> 106321 error argv "node" "/usr/local/bin/npm" "install" "ionic-minify" "--save-dev"
> 106322 error node v0.12.4
> 106323 error npm  v2.13.3
> 106324 error code ELIFECYCLE
> 106325 error ionic-minify@2.0.9 postinstall: `node scripts/install.js`
> 106325 error Exit status 1
> 106326 error Failed at the ionic-minify@2.0.9 postinstall script 'node scripts/install.js'.
> 106326 error This is most likely a problem with the ionic-minify package,
> 106326 error not with npm itself.
> 106326 error Tell the author that this fails on your system:
> 106326 error     node scripts/install.js
> 106326 error You can get their info via:
> 106326 error     npm owner ls ionic-minify
> 106326 error There is likely additional logging output above.
> 106327 verbose exit [ 1, true ]

**Comment by Kurtz1993** [comment] 2016-08-12 03:31
Let me dig into this a little bit more.
Which OS are you using?

**Comment by snout-o** [comment] 2016-08-12 09:52
Thanks for the reply. I'm on Mac OS X El Capitan 10.11.6

**Comment by Kurtz1993** [comment] 2016-08-13 15:19
Couldn't reproduce the error (I could only install 0.12.15) on OS X El Capitan 10.11.6
Installed without errors. Any special configuration you got on your machine?

![screen shot 2016-08-13 at 10 18 29 am](https://cloud.githubusercontent.com/assets/5412470/17643958/64ade8ea-613f-11e6-8b3f-3f3ef59cff97.png)

**Comment by snout-o** [comment] 2016-08-14 05:11
Not that I'm aware of, although Ionic does seem to want to lock permissions on my project folder hence the need to use sudo. I'll run the npm command again and check if the error message is any more useful than the log details and get back to you.

**Comment by Kurtz1993** [comment] 2016-08-25 15:26
Any update on this @sibbaldl ?

**Comment by snout-o** [comment] 2016-08-27 05:22
Hi 

Sorry for being crap getting back to you on this I'll take a look tomorrow and see if anything is unusual. All I can think of is permissions  - maybe it's the gulp watch that adds restrictive permissions to the folders and that could be screwing the install. Is there a particular command I can run to make sure I get as much info as possible (think I was already running verbose tho)?

Cheers

Lee

**Comment by snout-o** [comment] 2016-08-29 08:42
Hi

Just ran the command again and still failing - here’s the full output.

There’s a few deprecated notices in the output - could they be responsible?

Cheers

Lee

**Comment by Kurtz1993** [comment] 2016-08-29 23:47
I'm unable to see the output 😞

**Comment by snout-o** [comment] 2016-08-30 00:59
Oh. Really? Sorry, must be the github system scraping the email content. Here’s a link from my dropbox instead:

https://dl.dropboxusercontent.com/u/7810832/install-fail.jpg

Cheers

Lee

**Comment by Kurtz1993** [comment] 2016-08-30 01:02
Have you tried running it with sudo?

**Comment by Kurtz1993** [comment] 2016-08-30 01:03
Seems to be erroring with an EACCES, which may be the issue. Could you please try again with sudo and tell me if that does the trick? 😄

**Comment by snout-o** [comment] 2016-08-30 01:25
Yeah that was the first thing I tried originally after the initial error. I’ve ran it again though and here’s the new failed output:

https://dl.dropboxusercontent.com/u/7810832/sudo-install-fail.jpg

Here’s the perms for the “hooks" folder:

drwxrwxr-x+  5 root      admin      170 30 Aug 11:18 hooks

Could ownership be an issue, even if running under sudo?

Cheers

Lee

**Comment by Kurtz1993** [comment] 2016-08-30 01:26
It could be, my folder is owned by my user.

Try a chown

**Comment by snout-o** [comment] 2016-08-30 02:48
boom!

Copying uglify-js to your node_modules/ folder...
Ionic minify has been installed successfully! :)

Not only did I have to chown the folder but also the readme file within too (and maybe everything else - I applied new ownership to all of contents).

**Comment by Kurtz1993** [comment] 2016-08-30 03:07
Awesome!

So you applied a chown -R right?

🤔 weird error but glad it got fixed :)

I'm closing this issue after adding those comments in the readme.

Thanks so much!

---

Luis Rogelio Hernández López 
luis.hlopez@outlook.com

**Comment by snout-o** [comment] 2016-08-30 03:56
Happy we got to the bottom of the problem!

As I’m lazy I just went in to the Info panel of the folder and modified the permissions from there but I don’t see why using chown would be any different (although I’ve never actually used that command).

Best of luck and thanks for the tool!

**Comment by Kurtz1993** [comment] 2016-08-30 14:01
Added ownership information to the docs and closing this issue.

Again, thank you very much 😄

**Closed as completed by Kurtz1993** 2016-08-30 14:01 UTC
